apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-cluster
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
  - name: omada
    db: admin
    passwordSecretRef:
      name: mongodb-secret
      key: omada-password
    roles:
    - name: root
      db: admin
    scramCredentialsSecretName: mongodb-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    storage.wiredTiger.engineConfig.cacheSizeGB: 1
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              requests:
                cpu: "250m"
                memory: 1536Mi
              limits:
                cpu: "2"
                memory: 2Gi
          - name: mongodb-agent
            resources:
              requests:
                cpu: "100m"
                memory: 200Mi
              limits:
                cpu: "500m"
                memory: 500Mi
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: mongodb
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
  dataFrom:
  - extract:
      key: mongodb
