apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://hashicorp-vault.vault.svc.cluster.local:8200
      path: secret
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-role
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xako-cluster-repo
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: xako-cluster-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/ilyas-bouktrane/xako-cluster.git
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
  - extract:
      key: argocd
