apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: ddns-system
  labels:
    app: cloudflare-ddns
spec:
  selector:
    matchLabels:
      app: cloudflare-ddns
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cloudflare-ddns
        image: favonia/cloudflare-ddns:1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ "ALL" ]
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: cfapi-ddns-token
        - name: DOMAINS
          value: xako.net
        - name: PROXIED
          value: "true"
      restartPolicy: Always
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secret
  namespace: ddns-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-ddns-secret
  dataFrom:
  - extract:
      key: cloudflare
---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cloudflare-ddns
  namespace: ddns-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: cloudflare-ddns
  updatePolicy:
    updateMode: "Recreate"
