apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-secret
  namespace: valkey
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: valkey-secret
  dataFrom:
  - extract:
      key: valkey
