!
router bgp 65000
 bgp router-id 192.168.20.1
 no bgp ebgp-requires-policy
 bgp graceful-restart
 bgp bestpath as-path multipath-relax
 timers bgp 3 9
!
 neighbor TALOS-WORKERS peer-group
 neighbor TALOS-WORKERS remote-as 65001
 neighbor TALOS-WORKERS description Talos-Cilium-Workers
 neighbor TALOS-WORKERS password #${SECRET}#
 neighbor 192.168.20.21 peer-group TALOS-WORKERS
 neighbor 192.168.20.22 peer-group TALOS-WORKERS
 neighbor 192.168.20.23 peer-group TALOS-WORKERS
!
 address-family ipv4 unicast
  maximum-paths 3
  neighbor TALOS-WORKERS activate
  neighbor TALOS-WORKERS soft-reconfiguration inbound
  neighbor TALOS-WORKERS route-map TALOS-IN in
  neighbor TALOS-WORKERS route-map TALOS-OUT out
 exit-address-family
!
exit
!
route-map TALOS-IN permit 10
 match ip address prefix-list TALOS-LB-VIP
exit
!
route-map TALOS-OUT deny 10
exit
!
ip prefix-list TALOS-LB-VIP seq 5 permit 192.168.20.20/32
ip prefix-list TALOS-LB-VIP seq 10 permit 192.168.20.99/32
!

