apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: hashicorp-vault-agent-injector-cfg
    jqPathExpressions:
    - '.webhooks[].clientConfig.caBundle'
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.33.0
    helm:
      releaseName: hashicorp-vault
      values: |
        server:
          ha:
            enabled: true
            raft:
              enabled: true
              setNodeId: true
        ui:
          enabled: true
          activeVaultPodOnly: true
          serviceType: ClusterIP
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
