apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-secret
  namespace: omada
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: omada-secret
  dataFrom:
  - extract:
      key: omada
---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: omada-controller
  namespace: omada
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: omada-controller
  updatePolicy:
    updateMode: "Recreate"
