repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: cilium
  url: https://helm.cilium.io/

releases:
- name: cilium
  namespace: kube-system
  createNamespace: true
  chart: cilium/cilium
  wait: true
  waitForJobs: true
  hooks:
  - events: [ "postsync" ]
    command: kubectl
    args: [ "apply", "-f", "cilium.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "cilium.yaml" ]
  values:
  - ipam:
      mode: kubernetes
  - kubeProxyReplacement: true
  - securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  - cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
  - k8sServiceHost: localhost
  - k8sServicePort: 7445
  - gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
  - l2announcements:
      enabled: true
  - bgpControlPlane:
      enabled: true

- name: argocd
  namespace: argocd
  createNamespace: true
  chart: argo/argo-cd
  values:
  - redis-ha:
      enabled: true
  - controller:
      replicas: 1
  - server:
      replicas: 2
  - repoServer:
      replicas: 2
  - applicationSet:
      replicas: 2
