repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: cilium
  url: https://helm.cilium.io/
- name: longhorn
  url: https://charts.longhorn.io
- name: mongodb
  url: https://mongodb.github.io/helm-charts
- name: descheduler
  url: https://kubernetes-sigs.github.io/descheduler/
- name: seafile
  url: https://haiwen.github.io/seafile-helm-chart/repo
- name: mariadb-operator
  url: https://helm.mariadb.com/mariadb-operator
- name: valkey
  url: https://valkey.io/valkey-helm/
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: external-secrets
  url: https://charts.external-secrets.io

releases:
- name: cilium
  namespace: kube-system
  createNamespace: true
  chart: cilium/cilium
  wait: true
  waitForJobs: true
  hooks:
  - events: [ "postsync" ]
    command: kubectl
    args: [ "apply", "-f", "cilium.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "cilium.yaml" ]
  values:
  - ipam:
      mode: kubernetes
  - kubeProxyReplacement: true
  - securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  - cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
  - k8sServiceHost: localhost
  - k8sServicePort: 7445
  - gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
  - l2announcements:
      enabled: true

- name: argocd
  namespace: argocd
  createNamespace: true
  chart: argo/argo-cd
  values:
  - redis-ha:
      enabled: true
  - controller:
      replicas: 1
  - server:
      replicas: 2
  - repoServer:
      replicas: 2
  - applicationSet:
      replicas: 2

- name: hashicorp-vault
  chart: hashicorp/vault
  createNamespace: true
  namespace: vault
  wait: true
  waitForJobs: true
  needs:
  - kube-system/cilium
  values:
  - server:
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
    ui:
      enabled: true
      activeVaultPodOnly: true
      serviceType: ClusterIP

- name: external-secrets
  chart: external-secrets/external-secrets
  createNamespace: true
  namespace: external-secrets
  wait: true
  waitForJobs: true
  hooks:
  - events: [ "postsync" ]
    command: kubectl
    args: [ "apply", "-f", "external-secrets.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "external-secrets.yaml" ]
  needs:
  - kube-system/cilium
  - vault/hashicorp-vault

- name: cert-manager
  chart: oci://quay.io/jetstack/charts/cert-manager
  namespace: cert-manager
  createNamespace: true
  wait: true
  waitForJobs: true
  needs:
  - kube-system/cilium
  values:
  - crds:
      enabled: true
  - config:
      enableGatewayAPI: true

- name: origin-ca-issuer
  chart: oci://ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer
  namespace: cert-manager
  needs:
  - cert-manager/cert-manager
  hooks:
  - events: [ "postsync" ]
    command: kubectl
    args: [ "apply", "-f", "cert-manager.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "cert-manager.yaml" ]

- name: vertical-pod-autoscaler
  chart: cowboysysop/vertical-pod-autoscaler
  namespace: kube-system
  createNamespace: true
  needs:
  - kube-system/cilium

- name: longhorn
  namespace: longhorn-system
  createNamespace: true
  chart: longhorn/longhorn
  hooks:
  - events: [ "presync" ]
    command: kubectl
    args: [ "label", "--overwrite", "namespace", "longhorn-system", "pod-security.kubernetes.io/enforce=privileged" ]
  - events: [ "postsync" ]
    command: kubectl
    args: [ "apply", "-f", "longhorn.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "longhorn.yaml" ]
  needs:
  - kube-system/cilium
  wait: true
  waitForJobs: true
  values:
  - persistence:
      defaultClass: false

- name: mongodb-operator
  namespace: mongodb
  createNamespace: true
  chart: mongodb/community-operator
  wait: true
  waitForJobs: true
  needs:
  - kube-system/cilium
  - external-secrets/external-secrets
  hooks:
  - events: [ "postsync" ]
    command: kubectl
    args: [ "apply", "-f", "mongodb.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "mongodb.yaml" ]

- name: omada-controller
  namespace: omada
  createNamespace: true
  chart: oci://registry-1.docker.io/mbentley/omada-controller-helm
  needs:
  - mongodb/mongodb-operator
  - external-secrets/external-secrets
  hooks:
  - events: [ "presync" ]
    command: kubectl
    args: [ "apply", "-f", "omada.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "omada.yaml" ]
  values:
  - config:
      externalMongoDBUrlSecret:
        name: omada-secret
        key: mongodb-url
      timezone: America/Toronto
  - persistence:
      data:
        storageClassName: longhorn
        size: 10Gi
      logs:
        storageClass: longhorn # bug - tmp
        size: 5Gi

- name: mariadb-operator-crds
  chart: mariadb-operator/mariadb-operator-crds
  createNamespace: true
  namespace: mariadb
  wait: true
  waitForJobs: true
  needs:
  - kube-system/cilium

- name: mariadb-operator
  chart: mariadb-operator/mariadb-operator
  createNamespace: true
  namespace: mariadb
  wait: true
  waitForJobs: true
  needs:
  - mariadb/mariadb-operator-crds
  values:
  - ha:
      enabled: true
      replicas: 3
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - mariadb-operator
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - mariadb-operator
          topologyKey: kubernetes.io/hostname
  - pdb:
      enabled: true
      maxUnavailable: 2

- name: mariadb-cluster
  chart: mariadb-operator/mariadb-cluster
  createNamespace: true
  namespace: mariadb
  wait: true
  waitForJobs: true
  needs:
  - mariadb/mariadb-operator
  - external-secrets/external-secrets
  hooks:
  - events: [ "presync" ]
    command: kubectl
    args: [ "apply", "-f", "mariadb.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "mariadb.yaml" ]
  values:
  - mariadb:
      rootPasswordSecretKeyRef:
        name: mariadb-secret
        key: root-password
        generate: false
      storage:
        size: 10Gi
    databases:
    - name: seafile-db
    - name: seahub-db
    - name: ccnet-db
    users:
    - name: seafile
      passwordSecretKeyRef:
        name: mariadb-secret
        key: seafile-password
      maxUserConnections: 0
    grants:
    - name: seafile
      privileges:
      - "ALL PRIVILEGES"
      username: seafile

- name: valkey
  chart: valkey/valkey
  createNamespace: true
  namespace: valkey
  wait: true
  waitForJobs: true
  needs:
  - kube-system/cilium
  - external-secrets/external-secrets
  hooks:
  - events: [ "presync" ]
    command: kubectl
    args: [ "apply", "-f", "valkey.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "valkey.yaml" ]
  values:
  - replica:
      enabled: true
      replicas: 2
      persistence:
        size: 1Gi
  - podDisruptionBudget:
      enabled: true
      minAvailable: 1
  - auth:
      enabled: true
      usersExistingSecret: "valkey-secret"
      aclUsers:
        default:
          permissions: "~* &* +@all"

- name: seafile-app
  chart: seafile/ce
  version: 13.0
  createNamespace: true
  namespace: seafile
  needs:
  - mariadb/mariadb-cluster
  - valkey/valkey
  - external-secrets/external-secrets
  hooks:
  - events: [ "presync" ]
    command: kubectl
    args: [ "apply", "-f", "seafile.yaml" ]
  - events: [ "postuninstall" ]
    command: kubectl
    args: [ "delete", "-f", "seafile.yaml" ]
  values:
  - seafile:
      configs:
        seafileDataVolume:
          storageClassName: longhorn
          storage: 100Gi
      env:
        TIME_ZONE: "America/Toronto"
        SEAFILE_SERVER_HOSTNAME: "drive.xako.net"
        SEAFILE_SERVER_PROTOCOL: "https"
        INIT_SEAFILE_ADMIN_EMAIL: "xakodelako@xako.net"
        REDIS_HOST: "valkey.valkey.svc.cluster.local"
        SEAFILE_MYSQL_DB_HOST: "mariadb-cluster-primary.mariadb.svc.cluster.local"
        SEAFILE_MYSQL_DB_CCNET_DB_NAME: "ccnet-db"
        SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "seafile-db"
        SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: "seahub-db"
