apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ilyas-bouktrane/xako-cluster.git
    targetRevision: HEAD
    path: k8s/apps/
    directory:
      recurse: true
      include: "**/application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xako-cluster-repo
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: xako-cluster-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/ilyas-bouktrane/xako-cluster.git
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
  - extract:
      key: argocd
