apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
  namespace: gateway-system
  annotations:
    cert-manager.io/issuer: cloudflare-origin-issuer
    cert-manager.io/issuer-kind: ClusterOriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.xako.net"
    tls:
      mode: Terminate
      certificateRefs:
      - name: xako-net-tls
    allowedRoutes:
      namespaces:
        from: All
---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-group: cert-manager.io
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.lan.xako.net"
    tls:
      mode: Terminate
      certificateRefs:
      - name: xako-lan-tls
    allowedRoutes:
      namespaces:
        from: All
---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: external-gateway-ip
spec:
  blocks:
  - cidr: "192.168.20.20/32"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: "gateway-system"
      io.kubernetes.service.name: "cilium-gateway-external-gateway"
---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: internal-gateway-ip
spec:
  blocks:
  - cidr: "192.168.20.99/32"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: "gateway-system"
      io.kubernetes.service.name: "cilium-gateway-internal-gateway"
---

apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  bgpInstances:
  - name: "instance-65000"
    localASN: 65001
    peers:
    - name: "unifi-router"
      peerASN: 65000
      autoDiscovery:
        mode: "DefaultGateway"
        defaultGateway:
          addressFamily: ipv4
      peerConfigRef:
        name: "cilium-peer"
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bgp-auth-secret
  namespace: kube-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bgp-auth-secret
  dataFrom:
  - extract:
      key: cilium-bgp
---

apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
---

apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
    selector:
      matchLabels:
        io.kubernetes.service.namespace: gateway-system
---


