apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-http
  namespace: gateway-system
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: ClusterOriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.xako.net"
    tls:
      mode: Terminate
      certificateRefs:
      - name: xako-net-tls
    allowedRoutes:
      namespaces:
        from: All
---

apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: arp-policy
  namespace: gateway-system
spec:
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-ip
  namespace: gateway-system
spec:
  blocks:
  - cidr: "192.168.20.20/32"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.namespace": "gateway-system"
---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: omada-ip
  namespace: gateway-system
spec:
  blocks:
  - cidr: "192.168.20.30/32"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.namespace": "omada"
